# Generated by Django 2.1.1 on 2019-04-22 15:47

from django.db import migrations, models
import picT.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=picT.models.Img.image_upload_to)),
            ],
        ),
    ]
