# Generated by Django 2.1.1 on 2019-04-23 08:05

from django.db import migrations, models
import picT.models


class Migration(migrations.Migration):

    dependencies = [
        ('picT', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.ImageField(upload_to=picT.models.Img2.image_upload_to)),
            ],
        ),
    ]
